### ISSUE TITLE
Cannot read property 'prototype' of undefined (superCtor)

### ISSUE THREAD

**Issue by ChernKiat** [AroLeaf/WaifuSocket#2]
...\waifulabs.js:72407
    ctor.prototype = Object.create(superCtor.prototype, {
                                             ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.inherits (...\waifulabs.js:72407:46)
    at Object../node_modules/←[4mbrowserify-zlib←[24m/lib/index.js (...\waifulabs.js:19061:6)
    at __webpack_require__ (...\waifulabs.js:82137:42)
    at Object../node_modules/←[4mzlib←[24m/lib/zlib.js (...\waifulabs.js:81842:18)
    at __webpack_require__ (...\waifulabs.js:82137:42)
    at Object../node_modules/←[4mws←[24m/lib/permessage-deflate.js (...\waifulabs.js:73888:14)
    at __webpack_require__ (...\waifulabs.js:82137:42)
    at Object../node_modules/←[4mws←[24m/lib/receiver.js (...\waifulabs.js:74413:27)
    at __webpack_require__ (...\waifulabs.js:82137:42)
    at Module../node_modules/←[4mws←[24m/wrapper.mjs (...\waifulabs.js:82024:74)

**Comment by AroLeaf** [comment]
After some searching I'm pretty sure this is an issue on webpack's side, or at least not something I can fix easily myself.

**Comment by ChernKiat** [comment]
Do you mind share what you put in the token part?

**Comment by AroLeaf** [comment]
Do you mean the cookie parameter for `.login()`? You put your `user_remember_me` cookie for https://waifulabs.com there. If you mean something else, please explain.

**Comment by ChernKiat** [comment]
Ya, but I can only find __stripe_mid, _ga, _gid, _waifulab_key, anything else? Sorry if it is a newbie question, I tried googling user_remember_me but nothing useful popout...

**Comment by AroLeaf** [comment]
Like the name suggests, you'll need to check the "remember me" checkbox when logging in, in case you didn't do that.

**Comment by ChernKiat** [comment]
Thank you. Hidden gem project. Does images you generated have watermark too?

**Comment by AroLeaf** [comment]
this package simply connects to the same websocket the website connects to, so just like on the website, small images (from `genGrid`) won't have watermarks, and big images (from `genBig`) will have watermarks
